"""empty message

Revision ID: 2d3b5ac422d6
Revises: 66a4d4098e82
Create Date: 2019-06-20 18:52:32.916529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3b5ac422d6'
down_revision = '66a4d4098e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
