"""empty message

Revision ID: 66a4d4098e82
Revises: 5fb98fb466d3
Create Date: 2019-06-20 18:47:06.440580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a4d4098e82'
down_revision = '5fb98fb466d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'id')
    # ### end Alembic commands ###
